#!/usr/bin/env python3
"""Build content/store_links.json (slug -> [{service, url}]) from
  1. the verified store_links already in the DistroKid catalog (incl. our collected youtube_music links), and
  2. /workspace/hyperfollow_scrape.json (links listed on each release's HyperFollow page, scraped with headless Chrome).
Existing links win on conflict; conflicts are printed. URLs are normalized to https; affiliate params are kept as is.
Usage: python3 tools/merge_store_links.py [--catalog PATH] [--scrape PATH] [--drop slug:Service ...]
"""
import argparse, json, re, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_data import slugify, clean_stores, ARTIST

ROOT = Path(__file__).resolve().parent.parent
CANON = {"Amazon": "Amazon Music", "amazon": "Amazon Music", "youtube_music": "YouTube Music", "Apple Music": "Apple Music",
         "iTunes": "iTunes", "Spotify": "Spotify", "Deezer": "Deezer", "iHeartRadio": "iHeartRadio", "Tidal": "TIDAL", "TIDAL": "TIDAL"}

def https(u):
    return "https://" + u[len("http://"):] if u.startswith("http://") else u

def key(u):
    """Identity of a link for conflict checks: host + path (query/affiliate params ignored)."""
    m = re.match(r"https?://([^/?#]+)([^?#]*)", u)
    return (m[1].lower().removeprefix("www."), m[2].rstrip("/")) if m else u

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", default="/workspace/bfo_mantis_catalog.json")
    ap.add_argument("--scrape", default="/workspace/hyperfollow_scrape.json")
    ap.add_argument("--drop", nargs="*", default=[], help="slug:Service pairs to drop (dead links)")
    a = ap.parse_args()
    cat = json.loads(Path(a.catalog).read_text()); scrape = json.loads(Path(a.scrape).read_text())
    drop = {tuple(x.split(":", 1)) for x in a.drop}
    used, out, conflicts, new, same_target = set(), {}, [], [], 0
    for r in cat:
        if ARTIST not in (r.get("artist") or []): continue
        slug = slugify(r["title"], used)
        links = {}
        for s in clean_stores(r.get("store_links"), r["type"].lower()):
            links[CANON.get(s["name"], s["name"])] = https(s["url"])
        for s in scrape.get(slug, []):
            name = CANON.get(s["service"], s["service"]); url = https(s["url"])
            if name in links:
                if key(links[name]) != key(url): conflicts.append((slug, name, links[name], url))
                else: same_target += 1
            else:
                links[name] = url; new.append((slug, name, url))
        for k in [k for k in links if (slug, k) in drop]: links.pop(k)
        out[slug] = [{"service": k, "url": v} for k, v in links.items()]
    data = {"_note": "Direct store links per release (slug -> [{service, url}]). Generated by tools/merge_store_links.py from the "
                     "catalog's verified links + the HyperFollow scrape; edit by hand if a link changes. Rebuild after editing."}
    data.update(out)
    (ROOT / "content" / "store_links.json").write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n")
    print(f"releases: {len(out)} | new links from HyperFollow: {len(new)} | same target, only params differ (kept existing): {same_target}")
    for n in new: print("  new:", *n)
    print("conflicts (kept existing):", conflicts or "none")

if __name__ == "__main__":
    main()
